---
runner:
  mypy:
    name: mypy
    cmd: mypy --strict --show-column-numbers inputremapper tests
    errorformat:
      - "%f:%l:%c: %m"

  pylint:
    name: pylint
    cmd: pylint inputremapper tests --extension-pkg-whitelist=evdev
    errorformat:
      - "%f:%l:%c: %t%n: %m"

  flake8:
    cmd: flake8 inputremapper tests
    format: flake8
