name: Pylint

on: [push]

jobs:
  build:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"] # min and max supported versions?
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint inputremapper --extension-pkg-whitelist=evdev || true
